"""T35 Stage 1 §5 fine-tune corpus (CPU; PRIVATE -> /tmp/nestquant/35-nq15/private/ft, never leaves the box).

Two sources, every window 2048 tokens with a decode mask (True = token generated by the model, i.e. a decode position):
  fp8dec   T33 fp8dec_run1b retired chains (FP8 model's own decode continuations of real agent prompts):
           tok.g{g}[off : off+P] = prompt (checked == tasks_all prompt), [off+P, off+P+n_dec) = decode tokens.
           window = the 2048 tokens ending at off+P+n_dec (prompt tail + the whole decode), mask = positions >= off+P.
           split by corpus: fp8dec-train -> train, fp8dec-heldout -> heldout (task_id disjoint, checked), tb21 excluded.
  sm120tf  T32 teacher-forced SM120 decode stretches (sm120tf.npy, 1899 windows, 7 tasks); mask = trace "dec".
           split by whole task: --sm-heldout tasks -> heldout, the rest -> train.
Output per split: {split}.tok.npy int32 [N, 2048], {split}.dec.npy bool [N, 2048], {split}.meta.jsonl, summary.json.
"""
import os, json, argparse, collections
import numpy as np

RUN = "/tmp/nestquant/33-search/ceiling/fp8dec_run1b/run"
SM = "/tmp/nestquant/32-gbdt-sal"
SEQ = 2048


def fp8dec(rows):
    meta = json.load(open(f"{RUN}/ckpt/meta.json"))["retired"]
    tasks = {t["id"]: t for t in json.load(open(f"{RUN}/tasks_all.json"))}
    toks = {}
    skip = collections.Counter()
    for r in meta:
        corp = r["id"].split("/")[0]
        split = {"fp8dec-train": "train", "fp8dec-heldout": "heldout"}.get(corp)
        if split is None:
            skip[corp] += 1; continue
        g, off, P, n = r["g"], r["off"], r["prompt_len"], r["n_dec"]
        if n < 1 or P + n < SEQ:
            skip["short"] += 1; continue
        if g not in toks:
            toks[g] = np.load(f"{RUN}/tok.g{g}.npy", mmap_mode="r")
        t = toks[g]
        tk = tasks[r["id"]]
        assert np.array_equal(np.asarray(t[off:off + P]), np.asarray(tk["prompt"], dtype=t.dtype)), r["id"]
        e = off + P + n
        assert e <= r["end"]
        w = np.asarray(t[e - SEQ:e], dtype=np.int32)
        dec = np.zeros(SEQ, bool); dec[SEQ - n:] = True
        rows[split].append((w, dec, dict(src="fp8dec", id=r["id"], task_id=tk["task_id"], group=tk.get("group"),
                                         P=P, n_dec=n, stopped=r.get("stopped"))))
    return skip


def sm120(rows, held):
    ids = np.load(f"{SM}/private/corpora/sm120tf.npy").reshape(-1, SEQ)
    mp = np.load(f"{SM}/private/corpora/sm120tf.map.npz")
    names = [str(x) for x in mp["names"]]
    decs = {n: np.load(f"{SM}/sm120_traces/serving/predictor/traces/{n}.npz")["dec"] for n in names}
    toks = {n: np.load(f"{SM}/sm120_traces/serving/predictor/traces/{n}.npz")["tok"] for n in names}
    for i, (ti, r0) in enumerate(zip(mp["task"], mp["row0"])):
        n = names[int(ti)]
        assert np.array_equal(toks[n][r0:r0 + SEQ].astype(np.int64), ids[i].astype(np.int64)), (n, r0)
        dec = decs[n][r0:r0 + SEQ].astype(bool)
        split = "heldout" if n in held else "train"
        rows[split].append((ids[i].astype(np.int32), dec, dict(src="sm120tf", task=n, row0=int(r0), n_dec=int(dec.sum()))))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="/tmp/nestquant/35-nq15/private/ft")
    ap.add_argument("--sm-heldout", default="formal-crypto,sound-change-cascade")
    ap.add_argument("--no-sm120", action="store_true")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    rows = {"train": [], "heldout": []}
    skip = fp8dec(rows)
    tr = {m["task_id"] for _, _, m in rows["train"] if m["src"] == "fp8dec"}
    ho = {m["task_id"] for _, _, m in rows["heldout"] if m["src"] == "fp8dec"}
    assert not tr & ho, f"task overlap {len(tr & ho)}"
    if not a.no_sm120:
        sm120(rows, set(a.sm_heldout.split(",")))
    summ = dict(skipped=dict(skip), fp8dec_task_overlap=0)
    for split, R in rows.items():
        np.save(f"{a.out}/{split}.tok.npy", np.stack([w for w, _, _ in R]))
        np.save(f"{a.out}/{split}.dec.npy", np.stack([d for _, d, _ in R]))
        with open(f"{a.out}/{split}.meta.jsonl", "w") as f:
            for _, _, m in R:
                f.write(json.dumps(m) + "\n")
        by = collections.defaultdict(lambda: [0, 0])
        for _, d, m in R:
            by[m["src"]][0] += 1; by[m["src"]][1] += int(d.sum())
        summ[split] = {k: dict(windows=v[0], dec_tokens=v[1]) for k, v in by.items()}
    json.dump(summ, open(f"{a.out}/summary.json", "w"), indent=1)
    print(json.dumps(summ, indent=1))


if __name__ == "__main__":
    main()
